/* 
 * @(#)PendingNotificationQueue.java        1.0
 *
 * This file has been auto-generated by JNC, the
 * Java output format plug-in of pyang.
 * Origin: module "tailf-confd-monitoring", revision: "2013-06-14".
 */

package com.airlenet.yang.model.tailfConfdMonitoring.confdState.internal.cdb.datastore;

import com.airlenet.yang.model.tailfCommonMonitoring.TfcgPrefix;
import com.airlenet.yang.model.tailfConfdMonitoring.confdState.internal.cdb.datastore.pendingNotificationQueue.Notification;
import com.tailf.jnc.Element;
import com.tailf.jnc.ElementChildrenIterator;
import com.tailf.jnc.JNCException;
import com.tailf.jnc.YangElement;

import java.util.ArrayList;
import java.util.List;

/**
 * This class represents an element from 
 * the namespace http://tail-f.com/yang/confd-monitoring
 * generated to "src/main/java/com.airlenet.yang.model/tailfConfdMonitoring/confdState/internal/cdb/datastore/pending-notification-queue"
 * <p>
 * See line 727 in
 * src/main/yang/module/tailf/tailf-common-monitoring.yang
 *
 * @version 1.0
 * @author Auto Generated
 */
public class PendingNotificationQueue extends YangElement {

    private static final long serialVersionUID = 1L;

    /**
     * Constructor for an empty PendingNotificationQueue object.
     */
    public PendingNotificationQueue() {
        super(TfcgPrefix.NAMESPACE, "pending-notification-queue");
    }

    /**
     * Clones this object, returning an exact copy.
     * @return A clone of the object.
     */
    public PendingNotificationQueue clone() {
        return (PendingNotificationQueue)cloneContent(new PendingNotificationQueue());
    }

    /**
     * Clones this object, returning a shallow copy.
     * @return A clone of the object. Children are not included.
     */
    public PendingNotificationQueue cloneShallow() {
        return (PendingNotificationQueue)cloneShallowContent(new PendingNotificationQueue());
    }

    /**
     * @return An array with the identifiers of any key children
     */
    public String[] keyNames() {
        return null;
    }

    /**
     * @return An array with the identifiers of any children, in order.
     */
    public String[] childrenNames() {
        return new String[] {
            "notification",
        };
    }

    /* Access methods for list child: "notification". */

    /**
     * Gets list entry "notification", with specified keys.
     */
    public Notification getNotification() throws JNCException {
        String path = "notification";
        return (Notification)searchOne(path);
    }

    /**
     * Iterator method for the list "notification".
     * @return An iterator for the list.
     */
    public ElementChildrenIterator notificationIterator() {
        return new ElementChildrenIterator(children, "notification");
    }

    /**
     * List method for the list "notification".
     * @return An List for the list.
     */
    public List<Notification> getNotificationList() {
        List<Notification> list = new ArrayList<>();
        ElementChildrenIterator iterator = notificationIterator();
        if(iterator==null){
            return null;
        }
        while (iterator.hasNext()){
            Notification next =(Notification) iterator.next();
            list.add(next);
        }
        return list;
    }

    /**
     * Adds list entry "notification", using an existing object.
     * @param notification The object to add.
     * @return The added child.
     */
    public Notification addNotification(Notification notification)
            throws JNCException {
        insertChild(notification, childrenNames());
        return notification;
    }

    /**
     * Adds list entry "notification".
     * This method is used for creating subtree filters.
     * @return The added child.
     */
    public Notification addNotification() throws JNCException {
        Notification notification = new Notification();
        insertChild(notification, childrenNames());
        return notification;
    }

    /**
     * Deletes list entry "notification", with specified keys.
     */
    public void deleteNotification() throws JNCException {
        String path = "notification";
        delete(path);
    }

    /**
     * Support method for addChild.
     * Adds a child to this object.
     * 
     * @param child The child to add
     */
    public void addChild(Element child) {
        super.addChild(child);
    }

}
