/* 
 * @(#)HaNodeId.java        1.0
 *
 * This file has been auto-generated by JNC, the
 * Java output format plug-in of pyang.
 * Origin: module "tailf-common-monitoring", revision: "2013-06-14".
 */

package com.airlenet.yang.model.tailfCommonMonitoring;

import com.tailf.jnc.YangException;
import com.tailf.jnc.YangString;

/**
 * This class represents an element from 
 * the namespace 
 * generated to "src/main/java/com.airlenet.yang.model/tailfCommonMonitoring/ha-node-id"
 * <p>
 * See line 62 in
 * src/main/yang/module/tailf/tailf-common-monitoring.yang
 *
 * @version 1.0
 * @author Auto Generated
 */
public class HaNodeId extends YangString {

    private static final long serialVersionUID = 1L;

    /**
     * Constructor for HaNodeId object from a string.
     * @param value Value to construct the HaNodeId from.
     */
    public HaNodeId(String value) throws YangException {
        super(value);
        check();
    }

    /**
     * Sets the value using a string value.
     * @param value The value to set.
     */
    public void setValue(String value) throws YangException {
        super.setValue(value);
        check();
    }

    /**
     * Checks all restrictions (if any).
     */
    public void check() throws YangException {
    }

}
