/* 
 * @(#)Variable.java        1.0
 *
 * This file has been auto-generated by JNC, the
 * Java output format plug-in of pyang.
 * Origin: module "tailf-kicker", revision: "2016-11-24".
 */

package com.airlenet.yang.model.tailfKicker.kickers.dataKicker;

import com.airlenet.yang.model.ietfYangTypes.Xpath10;
import com.airlenet.yang.model.tailfKicker.KickerPrefix;
import com.tailf.jnc.Element;
import com.tailf.jnc.JNCException;
import com.tailf.jnc.Leaf;
import com.tailf.jnc.YangElement;
import com.tailf.jnc.YangString;

/**
 * This class represents an element from 
 * the namespace http://tail-f.com/ns/kicker
 * generated to "src/main/java/com.airlenet.yang.model/tailfKicker/kickers/dataKicker/variable"
 * <p>
 * See line 129 in
 * src/main/yang/module/tailf/tailf-kicker.yang
 *
 * @version 1.0
 * @author Auto Generated
 */
public class Variable extends YangElement {

    private static final long serialVersionUID = 1L;

    /**
     * Constructor for an empty Variable object.
     */
    public Variable() {
        super(KickerPrefix.NAMESPACE, "variable");
    }

    /**
     * Constructor for an initialized Variable object,
     * 
     * @param nameValue Key argument of child.
     */
    public Variable(YangString nameValue) throws JNCException {
        super(KickerPrefix.NAMESPACE, "variable");
        Leaf name = new Leaf(KickerPrefix.NAMESPACE, "name");
        name.setValue(nameValue);
        insertChild(name, childrenNames());
    }

    /**
     * Constructor for an initialized Variable object,
     * with String keys.
     * @param nameValue Key argument of child.
     */
    public Variable(String nameValue) throws JNCException {
        super(KickerPrefix.NAMESPACE, "variable");
        Leaf name = new Leaf(KickerPrefix.NAMESPACE, "name");
        name.setValue(new com.tailf.jnc.YangString(nameValue));
        insertChild(name, childrenNames());
    }

    /**
     * Clones this object, returning an exact copy.
     * @return A clone of the object.
     */
    public Variable clone() {
        Variable copy;
        try {
            copy = new Variable(getNameValue().toString());
        } catch (JNCException e) {
            copy = null;
        }
        return (Variable)cloneContent(copy);
    }

    /**
     * Clones this object, returning a shallow copy.
     * @return A clone of the object. Children are not included.
     */
    public Variable cloneShallow() {
        Variable copy;
        try {
            copy = new Variable(getNameValue().toString());
        } catch (JNCException e) {
            copy = null;
        }
        return (Variable)cloneShallowContent(copy);
    }

    /**
     * @return An array with the identifiers of any key children
     */
    public String[] keyNames() {
        return new String[] {
            "name",
        };
    }

    /**
     * @return An array with the identifiers of any children, in order.
     */
    public String[] childrenNames() {
        return new String[] {
            "name",
            "value",
        };
    }

    /* Access methods for leaf child: "name". */

    /**
     * Gets the value for child leaf "name".
     * @return The value of the leaf.
     */
    public com.tailf.jnc.YangString getNameValue() throws JNCException {
        return (com.tailf.jnc.YangString)getValue("name");
    }

    /**
     * Sets the value for child leaf "name",
     * using instance of generated typedef class.
     * @param nameValue The value to set.
     * @param nameValue used during instantiation.
     */
    public void setNameValue(com.tailf.jnc.YangString nameValue)
            throws JNCException {
        setLeafValue(KickerPrefix.NAMESPACE,
            "name",
            nameValue,
            childrenNames());
    }

    /**
     * Sets the value for child leaf "name",
     * using a String value.
     * @param nameValue used during instantiation.
     */
    public void setNameValue(String nameValue) throws JNCException {
        setNameValue(new com.tailf.jnc.YangString(nameValue));
    }

    /**
     * This method is used for creating a subtree filter.
     * The added "name" leaf will not have a value.
     */
    public void addName() throws JNCException {
        setLeafValue(KickerPrefix.NAMESPACE,
            "name",
            null,
            childrenNames());
    }

    /* Access methods for optional leaf child: "value". */

    /**
     * Gets the value for child leaf "value".
     * @return The value of the leaf.
     */
    public com.airlenet.yang.model.ietfYangTypes.Xpath10 getValueValue()
            throws JNCException {
        return (com.airlenet.yang.model.ietfYangTypes.Xpath10)getValue("value");
    }

    /**
     * Sets the value for child leaf "value",
     * using a JNC type value.
     * @param valueValue The value to set.
     * @param valueValue used during instantiation.
     */
    public void setValueValue(com.airlenet.yang.model.ietfYangTypes.Xpath10 valueValue)
            throws JNCException {
        setLeafValue(KickerPrefix.NAMESPACE,
            "value",
            valueValue,
            childrenNames());
    }

    /**
     * Sets the value for child leaf "value",
     * using a String value.
     * @param valueValue used during instantiation.
     */
    public void setValueValue(String valueValue) throws JNCException {
        setValueValue(new com.airlenet.yang.model.ietfYangTypes.Xpath10(valueValue));
    }

    /**
     * Unsets the value for child leaf "value".
     */
    public void unsetValueValue() throws JNCException {
        delete("value");
    }

    /**
     * This method is used for creating a subtree filter.
     * The added "value" leaf will not have a value.
     */
    public void addValue() throws JNCException {
        setLeafValue(KickerPrefix.NAMESPACE,
            "value",
            null,
            childrenNames());
    }

    /**
     * Marks the leaf "value" with operation "replace".
     */
    public void markValueReplace() throws JNCException {
        markLeafReplace("value");
    }

    /**
     * Marks the leaf "value" with operation "merge".
     */
    public void markValueMerge() throws JNCException {
        markLeafMerge("value");
    }

    /**
     * Marks the leaf "value" with operation "create".
     */
    public void markValueCreate() throws JNCException {
        markLeafCreate("value");
    }

    /**
     * Marks the leaf "value" with operation "delete".
     */
    public void markValueDelete() throws JNCException {
        markLeafDelete("value");
    }

    /**
     * Marks the leaf "value" with operation "remove".
     */
    public void markValueRemove() throws JNCException {
        markLeafRemove("value");
    }

    /**
     * Support method for addChild.
     * Adds a child to this object.
     * 
     * @param child The child to add
     */
    public void addChild(Element child) {
        super.addChild(child);
    }

}
