/* 
 * @(#)Listen.java        1.0
 *
 * This file has been auto-generated by JNC, the
 * Java output format plug-in of pyang.
 * Origin: module "tailf-confd-monitoring", revision: "2013-06-14".
 */

package com.airlenet.yang.model.tailfConfdMonitoring.confdState.cli;

import com.airlenet.yang.model.tailfCommonMonitoring.TfcgPrefix;
import com.airlenet.yang.model.tailfConfdMonitoring.confdState.cli.listen.Ssh;
import com.tailf.jnc.Element;
import com.tailf.jnc.ElementChildrenIterator;
import com.tailf.jnc.JNCException;
import com.tailf.jnc.YangElement;

import java.util.ArrayList;
import java.util.List;

/**
 * This class represents an element from 
 * the namespace http://tail-f.com/yang/confd-monitoring
 * generated to "src/main/java/com.airlenet.yang.model/tailfConfdMonitoring/confdState/cli/listen"
 * <p>
 * See line 404 in
 * src/main/yang/module/tailf/tailf-common-monitoring.yang
 *
 * @version 1.0
 * @author Auto Generated
 */
public class Listen extends YangElement {

    private static final long serialVersionUID = 1L;

    /**
     * Constructor for an empty Listen object.
     */
    public Listen() {
        super(TfcgPrefix.NAMESPACE, "listen");
    }

    /**
     * Clones this object, returning an exact copy.
     * @return A clone of the object.
     */
    public Listen clone() {
        return (Listen)cloneContent(new Listen());
    }

    /**
     * Clones this object, returning a shallow copy.
     * @return A clone of the object. Children are not included.
     */
    public Listen cloneShallow() {
        return (Listen)cloneShallowContent(new Listen());
    }

    /**
     * @return An array with the identifiers of any key children
     */
    public String[] keyNames() {
        return null;
    }

    /**
     * @return An array with the identifiers of any children, in order.
     */
    public String[] childrenNames() {
        return new String[] {
            "ssh",
        };
    }

    /* Access methods for list child: "ssh". */

    /**
     * Gets list entry "ssh", with specified keys.
     */
    public Ssh getSsh() throws JNCException {
        String path = "ssh";
        return (Ssh)searchOne(path);
    }

    /**
     * Iterator method for the list "ssh".
     * @return An iterator for the list.
     */
    public ElementChildrenIterator sshIterator() {
        return new ElementChildrenIterator(children, "ssh");
    }

    /**
     * List method for the list "ssh".
     * @return An List for the list.
     */
    public List<Ssh> getSshList() {
        List<Ssh> list = new ArrayList<>();
        ElementChildrenIterator iterator = sshIterator();
        if(iterator==null){
            return null;
        }
        while (iterator.hasNext()){
            Ssh next =(Ssh) iterator.next();
            list.add(next);
        }
        return list;
    }

    /**
     * Adds list entry "ssh", using an existing object.
     * @param ssh The object to add.
     * @return The added child.
     */
    public Ssh addSsh(Ssh ssh) throws JNCException {
        insertChild(ssh, childrenNames());
        return ssh;
    }

    /**
     * Adds list entry "ssh".
     * This method is used for creating subtree filters.
     * @return The added child.
     */
    public Ssh addSsh() throws JNCException {
        Ssh ssh = new Ssh();
        insertChild(ssh, childrenNames());
        return ssh;
    }

    /**
     * Deletes list entry "ssh", with specified keys.
     */
    public void deleteSsh() throws JNCException {
        String path = "ssh";
        delete(path);
    }

    /**
     * Support method for addChild.
     * Adds a child to this object.
     * 
     * @param child The child to add
     */
    public void addChild(Element child) {
        super.addChild(child);
    }

}
