/* 
 * @(#)Files.java        1.0
 *
 * This file has been auto-generated by JNC, the
 * Java output format plug-in of pyang.
 * Origin: module "ietf-netconf-monitoring", revision: "2010-10-04".
 */

package com.airlenet.yang.model.ietfNetconfMonitoring.netconfState;

import com.airlenet.yang.model.ietfNetconfMonitoring.netconfState.files.File;
import com.airlenet.yang.model.tailfNetconfMonitoring.TncmPrefix;
import com.tailf.jnc.Element;
import com.tailf.jnc.ElementChildrenIterator;
import com.tailf.jnc.JNCException;
import com.tailf.jnc.YangElement;

import java.util.ArrayList;
import java.util.List;

/**
 * This class represents an element from 
 * the namespace urn:ietf:params:xml:ns:yang:ietf-netconf-monitoring
 * generated to "src/main/java/com.airlenet.yang.model/ietfNetconfMonitoring/netconfState/files"
 * <p>
 * See line 135 in
 * src/main/yang/module/tailf/tailf-netconf-monitoring.yang
 *
 * @version 1.0
 * @author Auto Generated
 */
public class Files extends YangElement {

    private static final long serialVersionUID = 1L;

    /**
     * Constructor for an empty Files object.
     */
    public Files() {
        super(TncmPrefix.NAMESPACE, "files");
        setDefaultPrefix();
        setPrefix(TncmPrefix.PREFIX);
    }

    /**
     * Clones this object, returning an exact copy.
     * @return A clone of the object.
     */
    public Files clone() {
        return (Files)cloneContent(new Files());
    }

    /**
     * Clones this object, returning a shallow copy.
     * @return A clone of the object. Children are not included.
     */
    public Files cloneShallow() {
        return (Files)cloneShallowContent(new Files());
    }

    /**
     * @return An array with the identifiers of any key children
     */
    public String[] keyNames() {
        return null;
    }

    /**
     * @return An array with the identifiers of any children, in order.
     */
    public String[] childrenNames() {
        return new String[] {
            "file",
        };
    }

    /* Access methods for list child: "file". */

    /**
     * Gets list entry "file", with specified keys.
     */
    public File getFile() throws JNCException {
        String path = "file";
        return (File)searchOne(path);
    }

    /**
     * Iterator method for the list "file".
     * @return An iterator for the list.
     */
    public ElementChildrenIterator fileIterator() {
        return new ElementChildrenIterator(children, "file");
    }

    /**
     * List method for the list "file".
     * @return An List for the list.
     */
    public List<File> getFileList() {
        List<File> list = new ArrayList<>();
        ElementChildrenIterator iterator = fileIterator();
        if(iterator==null){
            return null;
        }
        while (iterator.hasNext()){
            File next =(File) iterator.next();
            list.add(next);
        }
        return list;
    }

    /**
     * Adds list entry "file", using an existing object.
     * @param file The object to add.
     * @return The added child.
     */
    public File addFile(File file) throws JNCException {
        insertChild(file, childrenNames());
        return file;
    }

    /**
     * Adds list entry "file".
     * This method is used for creating subtree filters.
     * @return The added child.
     */
    public File addFile() throws JNCException {
        File file = new File();
        insertChild(file, childrenNames());
        return file;
    }

    /**
     * Deletes list entry "file", with specified keys.
     */
    public void deleteFile() throws JNCException {
        String path = "file";
        delete(path);
    }

    /**
     * Support method for addChild.
     * Adds a child to this object.
     * 
     * @param child The child to add
     */
    public void addChild(Element child) {
        super.addChild(child);
    }

}
