/* 
 * @(#)YanglibPrefix.java        1.0
 *
 * This file has been auto-generated by JNC, the
 * Java output format plug-in of pyang.
 * Origin: module "ietf-yang-library", revision: "2016-06-21".
 */

package com.airlenet.yang.model.ietfYangLibrary;

import com.tailf.jnc.JNCException;
import com.tailf.jnc.SchemaNode;
import com.tailf.jnc.SchemaParser;
import com.tailf.jnc.SchemaTree;
import com.tailf.jnc.Tagpath;
import com.tailf.jnc.YangElement;

import java.util.HashMap;

/**
 * The root class for namespace urn:ietf:params:xml:ns:yang:ietf-yang-library (accessible from 
 * IetfYangLibrary.NAMESPACE) with prefix "yanglibPrefix" (IetfYangLibrary.PREFIX).
 *
 * @version 1.0
 * @author Auto Generated
 */
public class YanglibPrefix {

    public static final String NAMESPACE = "urn:ietf:params:xml:ns:yang:ietf-yang-library";

    public static final String PREFIX = "yanglib";

    /**
     * Enable the elements in this namespace to be aware
     * of the data model and use the generated classes.
     */
    public static void enable() throws JNCException {
        YangElement.setPackage(NAMESPACE, "com.airlenet.yang.model.ietfYangLibrary");
        YanglibPrefix.registerSchema();
    }

    /**
     * Register the schema for this namespace in the global
     * schema table (CsTree) making it possible to lookup
     * CsNode entries for all tagpaths
     */
    public static void registerSchema() throws JNCException {
        SchemaParser parser = new SchemaParser();
        HashMap<Tagpath, SchemaNode> h = SchemaTree.create(NAMESPACE);
        parser.findAndReadFile("YanglibPrefix.schema", h, YanglibPrefix.class);
    }

}
