/* 
 * @(#)DemoPrefix.java        1.0
 *
 * This file has been auto-generated by JNC, the
 * Java output format plug-in of pyang.
 * Origin: module "Demo", revision: "unknown".
 */

package com.airlenet.yang.model.demo;

import com.tailf.jnc.JNCException;
import com.tailf.jnc.SchemaNode;
import com.tailf.jnc.SchemaParser;
import com.tailf.jnc.SchemaTree;
import com.tailf.jnc.Tagpath;
import com.tailf.jnc.YangElement;

import java.util.HashMap;

/**
 * The root class for namespace http://tail-f.com/ns/example/demo (accessible from 
 * Demo.NAMESPACE) with prefix "demoPrefix" (Demo.PREFIX).
 *
 * @version 1.0
 * @author Auto Generated
 */
public class DemoPrefix {

    public static final String NAMESPACE = "http://tail-f.com/ns/example/demo";

    public static final String PREFIX = "Demo";

    /**
     * Enable the elements in this namespace to be aware
     * of the data model and use the generated classes.
     */
    public static void enable() throws JNCException {
        YangElement.setPackage(NAMESPACE, "com.airlenet.yang.model.Demo");
        DemoPrefix.registerSchema();
    }

    /**
     * Register the schema for this namespace in the global
     * schema table (CsTree) making it possible to lookup
     * CsNode entries for all tagpaths
     */
    public static void registerSchema() throws JNCException {
        SchemaParser parser = new SchemaParser();
        HashMap<Tagpath, SchemaNode> h = SchemaTree.create(NAMESPACE);
        parser.findAndReadFile("DemoPrefix.schema", h, DemoPrefix.class);
    }

}
