/* 
 * @(#)CliTemplateString.java        1.0
 *
 * This file has been auto-generated by JNC, the
 * Java output format plug-in of pyang.
 * Origin: module "tailf-common", revision: "2017-01-26".
 */

package com.airlenet.yang.model.tailfCommon;

import com.tailf.jnc.YangException;
import com.tailf.jnc.YangString;

/**
 * This class represents an element from 
 * the namespace 
 * generated to "src/main/java/com.airlenet.yang.model/tailfCommon/cli-template-string"
 * <p>
 * See line 3022 in
 * src/main/yang/module/tailf/tailf-cli-extensions.yang
 *
 * @version 1.0
 * @author Auto Generated
 */
public class CliTemplateString extends YangString {

    private static final long serialVersionUID = 1L;

    /**
     * Constructor for CliTemplateString object from a string.
     * @param value Value to construct the CliTemplateString from.
     */
    public CliTemplateString(String value) throws YangException {
        super(value);
        check();
    }

    /**
     * Sets the value using a string value.
     * @param value The value to set.
     */
    public void setValue(String value) throws YangException {
        super.setValue(value);
        check();
    }

    /**
     * Checks all restrictions (if any).
     */
    public void check() throws YangException {
    }

}
