/* 
 * @(#)IpAddress.java        1.0
 *
 * This file has been auto-generated by JNC, the
 * Java output format plug-in of pyang.
 * Origin: module "ietf-inet-types", revision: "2013-07-15".
 */

package com.airlenet.yang.model.ietfInetTypes;

import com.tailf.jnc.YangException;
import com.tailf.jnc.YangUnion;

/**
 * This class represents an element from 
 * the namespace 
 * generated to "src/main/java/com.airlenet.yang.model/ietfInetTypes/ip-address"
 * <p>
 * See line 179 in
 * src/main/yang/module/ietf/ietf-inet-types.yang
 *
 * @version 1.0
 * @author Auto Generated
 */
public class IpAddress extends YangUnion {

    private static final long serialVersionUID = 1L;

    /**
     * Constructor for IpAddress object from a string.
     * @param value Value to construct the IpAddress from.
     */
    public IpAddress(String value) throws YangException {
        super(value,
            new String[] {
                "com.airlenet.yang.model.ietfInetTypes.Ipv4Address",
                "com.airlenet.yang.model.ietfInetTypes.Ipv6Address",
            }
        );
        check();
    }

    /**
     * Sets the value using a string value.
     * @param value The value to set.
     */
    public void setValue(String value) throws YangException {
        super.setValue(value);
        check();
    }

    /**
     * Checks all restrictions (if any).
     */
    public void check() throws YangException {
    }

}
